{"uuid": "8cd3b29c-3edb-4858-bc42-971b524e732f", "children": ["5805a860-e2e0-4e82-9e6d-9a570ecf3cd3"], "befores": [{"name": "test_verifyURL", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=131.0.6778.86)\nStacktrace:\n\tGetHandleVerifier [0x00007FF658D86CB5+28821]\n\t(No symbol) [0x00007FF658CF3840]\n\t(No symbol) [0x00007FF658B9578A]\n\t(No symbol) [0x00007FF658B6F4F5]\n\t(No symbol) [0x00007FF658C16247]\n\t(No symbol) [0x00007FF658C2ECE2]\n\t(No symbol) [0x00007FF658C0F0A3]\n\t(No symbol) [0x00007FF658BDA778]\n\t(No symbol) [0x00007FF658BDB8E1]\n\tGetHandleVerifier [0x00007FF6590BFCAD+3408013]\n\tGetHandleVerifier [0x00007FF6590D741F+3504127]\n\tGetHandleVerifier [0x00007FF6590CB5FD+3455453]\n\tGetHandleVerifier [0x00007FF658E4BDBB+835995]\n\t(No symbol) [0x00007FF658CFEB5F]\n\t(No symbol) [0x00007FF658CFA814]\n\t(No symbol) [0x00007FF658CFA9AD]\n\t(No symbol) [0x00007FF658CEA199]\n\tBaseThreadInitThunk [0x00007FFC53067374+20]\n\tRtlUserThreadStart [0x00007FFC543DCC91+33]\n\n", "trace": "  File \"C:\\Users\\shoeb.syed\\PycharmProjects\\pythonProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\shoeb.syed\\PycharmProjects\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\shoeb.syed\\PycharmProjects\\pythonProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shoeb.syed\\PycharmProjects\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shoeb.syed\\PycharmProjects\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shoeb.syed\\PycharmProjects\\pythonProject\\pytestcode\\test_day3Datadriven.py\", line 26, in test_verifyURL\n    driver.maximize_window()\n  File \"C:\\Users\\shoeb.syed\\PycharmProjects\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 532, in maximize_window\n    self.execute(command, None)\n  File \"C:\\Users\\shoeb.syed\\PycharmProjects\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 380, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\shoeb.syed\\PycharmProjects\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1732873382857, "stop": 1732873403518}], "start": 1732873382857, "stop": 1732873403675}