[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C97D0B6B10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7f9efe10db733b55b003d79f48611b27
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C97CF12180>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7f9efe10db733b55b003d79f48611b27
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C97DDAB5F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7f9efe10db733b55b003d79f48611b27